# Day 1 模块 3：第一次读取 CSV

这一模块排在 Python 基础之后。

前面已经学过变量、列表、if、for。

现在第一次把真实数据表读进 Python。

## 1. 什么是 CSV

CSV 可以理解成一种纯文本表格文件。它没有 Excel 那样的颜色和格式，但结构很适合程序读取。

## 1.1 CSV 读入示意图

先看一眼这张图，理解“CSV 文件是怎么变成 Python 里表格对象的”。

![CSV 到 DataFrame 示意图](day1_csv_to_dataframe_demo.png)

先抓住这句话：

- 左边是原始 CSV 文件
- 中间是 `pd.read_csv(...)`
- 右边是读进 Python 之后的表格对象 `df`

## 1.2 相对路径和绝对路径

在读取文件之前，先搞清楚一个很重要的概念：**路径**。

### 绝对路径
绝对路径就是“完整地址”，从电脑里的大位置一路写到文件名。

例如：

```python
D:/obi/熵学院/授课/机器学习-6小时/教学课程/day1/day1_cafe_sales.csv
```


### 相对路径
相对路径不是从整台电脑最外面开始写，而是从**当前工作位置**开始写。

例如，如果我们现在打开的就是 `day1` 文件夹，那么：

```python
"../../day1_cafe_sales.csv"
```

就表示：**在当前文件夹里找这个文件**。

---

上课时更常用相对路径，因为它更短，也更适合大家用同一套课程文件。

## 1.3 相对路径是从哪里开始算的

这件事特别容易卡住。

请先记住一句话：

> 相对路径不是从 notebook 文件名开始算，
> 而是从**当前打开的工作文件夹**开始算。

这次课程里，我们要求大家都用 VS Code 打开 `教学课程/day1` 这个文件夹。  
所以当我们写：

```python
day1_cafe_sales.csv
```

意思就是：

- 先看当前打开的位置是不是 `day1`
- 如果是，就在这个文件夹里找 `day1_cafe_sales.csv`

如果你打开错了位置，比如打开到了更上层文件夹，电脑就可能找不到这个文件。

所以“找不到 csv”时，先别急着改代码，先检查：

1. 左边文件栏里是不是打开了 `day1` 文件夹
2. `day1_cafe_sales.csv` 是不是和 notebook 在同一个教学目录里

这比乱改文件名更重要。

---

正因为不同同学有时会打开错文件夹，下面的代码才会准备几个可能的位置，尽量自动帮我们找到 csv 文件。

In [5]:
from pathlib import Path
import pandas as pd

csv_path = Path("day1_cafe_sales.csv")

candidate_paths = [
    Path('day1_cafe_sales.csv'),
    Path('day1') / 'day1_cafe_sales.csv',
    Path('教学课程') / 'day1' / 'day1_cafe_sales.csv',
]

for path in candidate_paths:
    if path.exists():
        csv_path = path
        break
else:
    raise FileNotFoundError('未找到 day1_cafe_sales.csv')

print(csv_path.resolve())

D:\obi\熵学院\授课\机器学习-6小时\教学课程\day1\day1_cafe_sales.csv

## 2. 用 pandas 读取数据

今天最重要的一行代码之一：`pd.read_csv(...)`。

In [6]:
df = pd.read_csv(csv_path)
print(type(df))

<class 'pandas.core.frame.DataFrame'>

## 3. 看前几行

第一眼看数据，不要急着算，先确认读进来的表长什么样。

In [3]:
df.head()

,day,weather,weather_label,temp,is_weekend,promotion,quality,price,location,competitors,holiday,sales
0,1,1,多云,33.5,0,1,8.27,24.5,5.78,2,0,3249
1,2,2,阴,6.7,0,1,9.57,22.0,9.96,0,0,4700
2,3,0,晴,23.4,0,0,7.11,27.9,7.28,5,0,2071
3,4,2,阴,6.4,0,0,6.65,23.0,9.74,3,0,2370
4,5,0,晴,11.9,0,0,8.60,31.8,9.17,2,0,2847

## 4. 看更多行

可以试试前 10 行，感受一下表格的稳定结构。

In [4]:
df.head(10)

,day,weather,weather_label,temp,is_weekend,promotion,quality,price,location,competitors,holiday,sales
0,1,1,多云,33.5,0,1,8.27,24.5,5.78,2,0,3249
1,2,2,阴,6.7,0,1,9.57,22.0,9.96,0,0,4700
2,3,0,晴,23.4,0,0,7.11,27.9,7.28,5,0,2071
3,4,2,阴,6.4,0,0,6.65,23.0,9.74,3,0,2370
4,5,0,晴,11.9,0,0,8.60,31.8,9.17,2,0,2847
5,6,2,阴,14.4,1,0,8.08,25.0,9.85,1,0,3591
6,7,4,大雨,26.8,1,0,8.17,30.3,9.81,4,0,1913
7,8,3,小雨,15.7,0,0,8.06,24.3,9.01,0,1,3771
8,9,1,多云,13.8,0,0,6.76,33.4,8.95,2,1,3090
9,10,0,晴,30.9,0,0,7.26,23.0,6.55,4,0,2436

## 5. 模块小结

这一模块先记住这几件事：

- 什么是 CSV
- 什么是 `pandas`
- 如何用 `pd.read_csv()` 把数据读进来
- 如何用 `head()` 看前几行